FROM alpine:20200428

RUN apk add --no-cache --upgrade chrony

COPY assets/chronyd/chrony.conf /etc/chrony/chrony.conf

HEALTHCHECK --interval=60s --timeout=5s CMD chronyc tracking > /dev/null

ENTRYPOINT ["/usr/sbin/chronyd"]
CMD ["-d", "-F", "0"]
